//go:build ignore

// This program fetches trust list fixtures from production endpoints
// and saves them to testdata/fixtures/ for offline testing.
//
// Usage:
//
//	go generate ./pkg/registry/walletcompat/
//
// The fetched fixtures are committed to the repository so tests can
// run without network access. Re-run go generate to refresh them.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

const (
	fixtureDir = "testdata/fixtures"

	// SIROS demo trust lists
	loteURL = "https://trust.siros.org/lote-demo.json"
	lotlURL = "https://trust.siros.org/list_of_trusted_lists-demo.json"
	tslURL  = "https://trust.siros.org/ewc-demo.xml"
)

var client = &http.Client{Timeout: 30 * time.Second}

func main() {
	if err := os.MkdirAll(fixtureDir, 0o755); err != nil {
		log.Fatalf("mkdir %s: %v", fixtureDir, err)
	}

	// Fetch LoTE JSON
	fmt.Println("Fetching LoTE from", loteURL)
	if err := fetchAndSave(loteURL, filepath.Join(fixtureDir, "lote-demo.json")); err != nil {
		log.Fatalf("fetch LoTE: %v", err)
	}

	// Fetch LoTL JSON and rewrite LoTELocation URLs to use {{BASE_URL}} placeholder
	fmt.Println("Fetching LoTL from", lotlURL)
	if err := fetchAndRewriteLoTL(lotlURL, filepath.Join(fixtureDir, "lotl-demo.json")); err != nil {
		log.Fatalf("fetch LoTL: %v", err)
	}

	// Fetch ETSI TSL XML (strip XML signature since validation fails on the demo data)
	fmt.Println("Fetching ETSI TSL from", tslURL)
	if err := fetchAndStripSignature(tslURL, filepath.Join(fixtureDir, "ewc-demo.xml")); err != nil {
		log.Fatalf("fetch TSL: %v", err)
	}

	// Write metadata
	meta := map[string]interface{}{
		"fetched_at": time.Now().UTC().Format(time.RFC3339),
		"sources": map[string]string{
			"lote-demo.json": loteURL,
			"lotl-demo.json": lotlURL,
			"ewc-demo.xml":   tslURL,
		},
		"note": "Generated by go generate. Re-run to refresh fixtures.",
	}
	metaJSON, _ := json.MarshalIndent(meta, "", "  ")
	if err := os.WriteFile(filepath.Join(fixtureDir, "metadata.json"), metaJSON, 0o644); err != nil {
		log.Fatalf("write metadata: %v", err)
	}

	fmt.Println("Fixtures written to", fixtureDir)
}

func fetchAndSave(url, dest string) error {
	resp, err := client.Get(url)
	if err != nil {
		return fmt.Errorf("GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: status %d", url, resp.StatusCode)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read body from %s: %w", url, err)
	}

	return os.WriteFile(dest, data, 0o644)
}

// fetchAndRewriteLoTL fetches the LoTL JSON and replaces absolute LoTELocation
// URLs with {{BASE_URL}}-prefixed relative paths so the test httptest server
// can serve them.
func fetchAndRewriteLoTL(url, dest string) error {
	resp, err := client.Get(url)
	if err != nil {
		return fmt.Errorf("GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: status %d", url, resp.StatusCode)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read body: %w", err)
	}

	// Rewrite known LoTE URLs to use placeholder.
	// The LoTL points to https://trust.siros.org/lote-demo.json
	// Rewrite to {{BASE_URL}}/lote-demo.json
	s := string(data)
	s = strings.ReplaceAll(s, "https://trust.siros.org/lote-demo.json", "{{BASE_URL}}/lote-demo.json")
	// Also handle any other trust.siros.org references
	s = strings.ReplaceAll(s, "https://trust.siros.org/", "{{BASE_URL}}/")

	return os.WriteFile(dest, []byte(s), 0o644)
}

// fetchAndStripSignature fetches XML, removes the <ds:Signature> or <Signature>
// element (which may not validate on demo data), and saves the result.
func fetchAndStripSignature(url, dest string) error {
	resp, err := client.Get(url)
	if err != nil {
		return fmt.Errorf("GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: status %d", url, resp.StatusCode)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read body from %s: %w", url, err)
	}

	// Strip XML Signature element (may use ds: prefix or not)
	re := regexp.MustCompile(`(?s)<(?:ds:)?Signature[^>]*>.*?</(?:ds:)?Signature>`)
	data = re.ReplaceAll(data, nil)

	return os.WriteFile(dest, data, 0o644)
}
