//go:build ignore

// This program fetches trust list fixtures from production endpoints
// and saves them to testdata/fixtures/ for offline testing.
//
// Usage:
//
//	go generate ./pkg/registry/walletcompat/
//
// The fetched fixtures are committed to the repository so tests can
// run without network access. Re-run go generate to refresh them.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

const (
	fixtureDir = "testdata/fixtures"

	// SIROS demo trust lists
	loteURL = "https://trust.siros.org/lote-demo.json"
	lotlURL = "https://trust.siros.org/list_of_trusted_lists-demo.json"
	tslURL  = "https://trust.siros.org/ewc-demo.xml"

	// OpenID Federation — realta trust anchor
	realtaBase = "https://realta.labb.sunet.se"
	oidfedDir  = "testdata/fixtures/oidfed"
)

var client = &http.Client{Timeout: 30 * time.Second}

func main() {
	if err := os.MkdirAll(fixtureDir, 0o755); err != nil {
		log.Fatalf("mkdir %s: %v", fixtureDir, err)
	}

	// Fetch LoTE JSON
	fmt.Println("Fetching LoTE from", loteURL)
	if err := fetchAndSave(loteURL, filepath.Join(fixtureDir, "lote-demo.json")); err != nil {
		log.Fatalf("fetch LoTE: %v", err)
	}

	// Fetch LoTL JSON and rewrite LoTELocation URLs to use {{BASE_URL}} placeholder
	fmt.Println("Fetching LoTL from", lotlURL)
	if err := fetchAndRewriteLoTL(lotlURL, filepath.Join(fixtureDir, "lotl-demo.json")); err != nil {
		log.Fatalf("fetch LoTL: %v", err)
	}

	// Fetch ETSI TSL XML (strip XML signature since validation fails on the demo data)
	fmt.Println("Fetching ETSI TSL from", tslURL)
	if err := fetchAndStripSignature(tslURL, filepath.Join(fixtureDir, "ewc-demo.xml")); err != nil {
		log.Fatalf("fetch TSL: %v", err)
	}

	// Write metadata
	meta := map[string]interface{}{
		"fetched_at": time.Now().UTC().Format(time.RFC3339),
		"sources": map[string]string{
			"lote-demo.json": loteURL,
			"lotl-demo.json": lotlURL,
			"ewc-demo.xml":   tslURL,
		},
		"note": "Generated by go generate. Re-run to refresh fixtures.",
	}

	// Fetch OpenID Federation fixtures from realta trust anchor
	fmt.Println("Fetching OpenID Federation fixtures from", realtaBase)
	oidfedSources, err := fetchOIDFedFixtures()
	if err != nil {
		log.Printf("WARNING: OIDFed fixture fetch failed: %v", err)
		log.Println("OIDFed fixtures will not be available for offline testing")
	} else {
		meta["sources"].(map[string]string)["oidfed/"] = realtaBase
		for k, v := range oidfedSources {
			meta["sources"].(map[string]string)["oidfed/"+k] = v
		}
	}

	metaJSON, _ := json.MarshalIndent(meta, "", "  ")
	if err := os.WriteFile(filepath.Join(fixtureDir, "metadata.json"), metaJSON, 0o644); err != nil {
		log.Fatalf("write metadata: %v", err)
	}

	fmt.Println("Fixtures written to", fixtureDir)
}

func fetchAndSave(url, dest string) error {
	resp, err := client.Get(url)
	if err != nil {
		return fmt.Errorf("GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: status %d", url, resp.StatusCode)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read body from %s: %w", url, err)
	}

	return os.WriteFile(dest, data, 0o644)
}

// fetchAndRewriteLoTL fetches the LoTL JSON and replaces absolute LoTELocation
// URLs with {{BASE_URL}}-prefixed relative paths so the test httptest server
// can serve them.
func fetchAndRewriteLoTL(url, dest string) error {
	resp, err := client.Get(url)
	if err != nil {
		return fmt.Errorf("GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: status %d", url, resp.StatusCode)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read body: %w", err)
	}

	// Rewrite known LoTE URLs to use placeholder.
	// The LoTL points to https://trust.siros.org/lote-demo.json
	// Rewrite to {{BASE_URL}}/lote-demo.json
	s := string(data)
	s = strings.ReplaceAll(s, "https://trust.siros.org/lote-demo.json", "{{BASE_URL}}/lote-demo.json")
	// Also handle any other trust.siros.org references
	s = strings.ReplaceAll(s, "https://trust.siros.org/", "{{BASE_URL}}/")

	return os.WriteFile(dest, []byte(s), 0o644)
}

// fetchAndStripSignature fetches XML, removes the <ds:Signature> or <Signature>
// element (which may not validate on demo data), and saves the result.
func fetchAndStripSignature(url, dest string) error {
	resp, err := client.Get(url)
	if err != nil {
		return fmt.Errorf("GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: status %d", url, resp.StatusCode)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read body from %s: %w", url, err)
	}

	// Strip XML Signature element (may use ds: prefix or not)
	re := regexp.MustCompile(`(?s)<(?:ds:)?Signature[^>]*>.*?</(?:ds:)?Signature>`)
	data = re.ReplaceAll(data, nil)

	return os.WriteFile(dest, data, 0o644)
}

// fetchOIDFedFixtures downloads OpenID Federation entity configurations and
// entity statements from the realta trust anchor, saving them as raw JWTs
// for use with httpmock in tests.
//
// Directory structure:
//
//	oidfed/
//	  manifest.json                   — maps entity IDs → fixture files + URLs
//	  entity_config_<host>.jwt        — entity configuration JWTs
//	  entity_statement_<host>.jwt     — entity statement JWTs (from TA fetch endpoint)
//	  list_<host>.json                — subordinate list JSON
func fetchOIDFedFixtures() (map[string]string, error) {
	if err := os.MkdirAll(oidfedDir, 0o755); err != nil {
		return nil, fmt.Errorf("mkdir %s: %w", oidfedDir, err)
	}

	sources := make(map[string]string)

	// 1. Fetch trust anchor entity configuration
	taConfigURL := realtaBase + "/.well-known/openid-federation"
	fmt.Printf("  Fetching TA config: %s\n", taConfigURL)
	if err := fetchAndSave(taConfigURL, filepath.Join(oidfedDir, "entity_config_realta.jwt")); err != nil {
		return nil, fmt.Errorf("fetch TA config: %w", err)
	}
	sources["entity_config_realta.jwt"] = taConfigURL

	// 2. Fetch subordinate list
	listURL := realtaBase + "/list"
	fmt.Printf("  Fetching TA list: %s\n", listURL)
	if err := fetchAndSave(listURL, filepath.Join(oidfedDir, "list_realta.json")); err != nil {
		return nil, fmt.Errorf("fetch TA list: %w", err)
	}
	sources["list_realta.json"] = listURL

	// Parse the list to discover subordinates
	listData, err := os.ReadFile(filepath.Join(oidfedDir, "list_realta.json"))
	if err != nil {
		return nil, fmt.Errorf("read list: %w", err)
	}
	var subordinates []string
	if err := json.Unmarshal(listData, &subordinates); err != nil {
		return nil, fmt.Errorf("parse list: %w", err)
	}

	// 3. For each subordinate, fetch entity statement from TA and leaf config
	for _, entityID := range subordinates {
		host := entityIDToHost(entityID)
		fmt.Printf("  Fetching subordinate: %s\n", entityID)

		// Entity statement from TA
		fetchURL := realtaBase + "/fetch?sub=" + entityID
		esFile := fmt.Sprintf("entity_statement_%s.jwt", host)
		if err := fetchAndSave(fetchURL, filepath.Join(oidfedDir, esFile)); err != nil {
			log.Printf("  WARNING: failed to fetch entity statement for %s: %v", entityID, err)
			continue
		}
		sources[esFile] = fetchURL

		// Leaf entity configuration
		leafConfigURL := entityID + "/.well-known/openid-federation"
		ecFile := fmt.Sprintf("entity_config_%s.jwt", host)
		if err := fetchAndSave(leafConfigURL, filepath.Join(oidfedDir, ecFile)); err != nil {
			log.Printf("  WARNING: failed to fetch entity config for %s: %v", entityID, err)
			continue
		}
		sources[ecFile] = leafConfigURL
	}

	// 4. Write manifest mapping entity IDs to fixture files and URLs
	type manifestEntry struct {
		EntityID               string `json:"entity_id"`
		EntityConfigFile       string `json:"entity_config_file"`
		EntityConfigURL        string `json:"entity_config_url"`
		EntityStatementFile    string `json:"entity_statement_file,omitempty"`
		EntityStatementURL     string `json:"entity_statement_url,omitempty"`
		EntityStatementFetchBy string `json:"entity_statement_fetch_by,omitempty"`
	}

	manifest := struct {
		TrustAnchor   string          `json:"trust_anchor"`
		ListFile      string          `json:"list_file"`
		ListURL       string          `json:"list_url"`
		Entities      []manifestEntry `json:"entities"`
		SubordinateOf map[string]string `json:"subordinate_of"`
	}{
		TrustAnchor:   realtaBase,
		ListFile:      "list_realta.json",
		ListURL:       listURL,
		SubordinateOf: make(map[string]string),
	}

	// Add trust anchor
	manifest.Entities = append(manifest.Entities, manifestEntry{
		EntityID:         realtaBase,
		EntityConfigFile: "entity_config_realta.jwt",
		EntityConfigURL:  taConfigURL,
	})

	// Add subordinates
	for _, entityID := range subordinates {
		host := entityIDToHost(entityID)
		esFile := fmt.Sprintf("entity_statement_%s.jwt", host)
		ecFile := fmt.Sprintf("entity_config_%s.jwt", host)

		// Only add if files exist
		if _, err := os.Stat(filepath.Join(oidfedDir, ecFile)); err != nil {
			continue
		}

		entry := manifestEntry{
			EntityID:               entityID,
			EntityConfigFile:       ecFile,
			EntityConfigURL:        entityID + "/.well-known/openid-federation",
			EntityStatementFile:    esFile,
			EntityStatementURL:     realtaBase + "/fetch?sub=" + entityID,
			EntityStatementFetchBy: realtaBase,
		}
		manifest.Entities = append(manifest.Entities, entry)
		manifest.SubordinateOf[entityID] = realtaBase
	}

	manifestJSON, _ := json.MarshalIndent(manifest, "", "  ")
	if err := os.WriteFile(filepath.Join(oidfedDir, "manifest.json"), manifestJSON, 0o644); err != nil {
		return nil, fmt.Errorf("write manifest: %w", err)
	}

	fmt.Printf("  OIDFed fixtures: %d entities (1 anchor + %d subordinates)\n",
		len(manifest.Entities), len(subordinates))

	return sources, nil
}

// entityIDToHost extracts the hostname from an entity ID URL for use in filenames.
func entityIDToHost(entityID string) string {
	s := strings.TrimPrefix(entityID, "https://")
	s = strings.TrimPrefix(s, "http://")
	s = strings.ReplaceAll(s, "/", "_")
	s = strings.ReplaceAll(s, ":", "_")
	return s
}
